### PR TITLE
Add grenade and other throwables

### PR DESCRIPTION
**Pull request by przemekmas**

### CODE REVIEW

**Comment by Gregcs96** [comment]
Misspelt grenade 👎

**Comment by vr10t** [comment]
I think we should make throwables usable by enemies as well. If we have enemies with ranged attacks it makes sense to use the same class instead of making a new EnemyThrowable.

**Comment by przemekmas** [comment]
> Misspelt grenade 👎

Fixed typo

**Comment by przemekmas** [comment]
> I think we should make throwables usable by enemies as well. If we have enemies with ranged attacks it makes sense to use the same class instead of making a new EnemyThrowable.

You should be able to easily reuse the code for enemies if you wanted to. However, for now, I will leave this alone as I think that we should keep it simple for now. If we want the zombies to have throwables then we will revisit this in the future.

**Review by arturp96 — APPROVED** [review]
Lgtm

**Pull request merged**
